/**
 * TerrainPlaceables.js - lightweight config for small placeable terrain assets
 * Each entry is id -> { label, imgPath, type }
 * type: 'path' (coexists with tokens) | 'structure' (exclusive)
 */
export const TERRAIN_PLACEABLES = {
  // scaleMode: 'contain' (fit inside tile, preserve aspect),
  //            'cover'   (cover tile, preserve aspect, may overflow),
  //            'stretch' (force exact tile dimensions, may distort)
  'path-dirt': {
    label: 'Dirt Path',
    img: 'assets/terrain/paths/dirt-path-tile.png',
    type: 'path',
    scaleMode: 'cover',
    baselineOffsetPx: 0,
  },
  'path-stone': {
    label: 'Stone Path',
    img: 'assets/terrain/paths/stone-path-tile.png',
    type: 'path',
    scaleMode: 'cover',
    baselineOffsetPx: 0,
  },
  'structure-crumbling-brick': {
    label: 'Crumbling Brick Wall',
    img: 'assets/terrain/structures/crumbling-brick-wall-topleft-to-bottomright.png',
    type: 'structure',
    scaleMode: 'contain',
    baselineOffsetPx: 0,
  },
};

export default { TERRAIN_PLACEABLES };

// Tree groups (multi-variant placeables). Each key below points to an array of
// image paths. The placeable system accepts `img` as either a string or an
// array; when an array is provided the tile selection algorithm will pick a
// variant deterministically for initial placement and `cyclePlaceableVariant`
// can be used to rotate through alternatives.
// These entries are intentionally named with the prefix `tree-` so UI/tooling
// can distinguish them from single-image placeables.
// Legacy tree frame arrays removed (2D sprites deprecated for plants)

const TREE_PLACEABLES = {
  'tree-green-deciduous': {
    label: 'Green Deciduous',
    img: null, // 2D legacy removed; use 3D model
    modelKey: 'common-broadleaf-1',
    type: 'plant',
    scaleMode: 'contain',
    baselineOffsetPx: 16,
  },
  'tree-green-conifer': {
    label: 'Green Conifer',
    img: null,
    modelKey: 'pine-conifer-1',
    type: 'plant',
    scaleMode: 'contain',
    baselineOffsetPx: 16,
  },
  'tree-green-willow': {
    label: 'Green Willow',
    img: null,
    modelKey: 'common-broadleaf-4',
    type: 'plant',
    scaleMode: 'contain',
    baselineOffsetPx: 16,
  },
  'tree-single-palm': {
    label: 'Single Palm',
    img: null,
    // Use palm-specific virtual model key; loader will alias to an existing base + apply transforms.
    modelKey: 'palm-single-a',
    type: 'plant',
    scaleMode: 'contain',
    baselineOffsetPx: 16,
  },
  'tree-double-palm': {
    label: 'Double Palm',
    img: null,
    modelKey: 'palm-double-a',
    type: 'plant',
    scaleMode: 'contain',
    baselineOffsetPx: 16,
  },
  'tree-green-oval': {
    label: 'Green Oval',
    img: null,
    modelKey: 'common-broadleaf-2',
    type: 'plant',
    scaleMode: 'contain',
    baselineOffsetPx: 16,
  },
  'tree-green-columnar': {
    label: 'Green Columnar',
    img: null,
    modelKey: 'pine-conifer-2',
    type: 'plant',
    scaleMode: 'contain',
    baselineOffsetPx: 16,
  },
  'tree-green-small': {
    label: 'Green Small',
    img: null,
    modelKey: 'pine-conifer-4',
    type: 'plant',
    scaleMode: 'contain',
    baselineOffsetPx: 16,
  },
  'tree-green-small-oval': {
    label: 'Green Small Oval',
    img: null,
    modelKey: 'pine-conifer-5',
    type: 'plant',
    scaleMode: 'contain',
    baselineOffsetPx: 16,
  },
  'tree-green-tall-columnar': {
    label: 'Green Tall Columnar',
    img: null,
    modelKey: 'pine-conifer-3',
    type: 'plant',
    scaleMode: 'contain',
    baselineOffsetPx: 16,
  },
  'tree-orange-deciduous': {
    label: 'Orange Deciduous',
    img: null,
    modelKey: 'common-broadleaf-3',
    type: 'plant',
    scaleMode: 'contain',
    baselineOffsetPx: 16,
  },
  'tree-yellow-willow': {
    label: 'Yellow Willow',
    img: null,
    modelKey: 'common-broadleaf-5',
    type: 'plant',
    scaleMode: 'contain',
    baselineOffsetPx: 16,
  },
  'tree-yellow-conifer': {
    label: 'Yellow Conifer',
    img: null,
    modelKey: 'pine-conifer-5',
    type: 'plant',
    scaleMode: 'contain',
    baselineOffsetPx: 16,
  },
  'tree-bare-deciduous': {
    label: 'Bare Deciduous',
    img: null,
    modelKey: 'twisted-bare-1',
    type: 'plant',
    scaleMode: 'contain',
    baselineOffsetPx: 16,
  },
  // --- New variant families (3D) ---
  // Virtual family selectors (user chooses one button; placement picks random variant each click)
  'family-birch': {
    label: 'Birch',
    type: 'plant-family',
    familyVariants: [
      'tree-birch-a',
      'tree-birch-b',
      'tree-birch-c',
      'tree-birch-d',
      'tree-birch-e',
    ],
    representativeModelKey: 'birch-2',
  },
  'family-cherry': {
    label: 'Cherry Blossom',
    type: 'plant-family',
    familyVariants: [
      'tree-cherry-a',
      'tree-cherry-b',
      'tree-cherry-c',
      'tree-cherry-d',
      'tree-cherry-e',
    ],
    representativeModelKey: 'cherry-2',
  },
  'family-dead': {
    label: 'Dead Tree',
    type: 'plant-family',
    familyVariants: ['tree-dead-a', 'tree-dead-b', 'tree-dead-c', 'tree-dead-d'],
    representativeModelKey: 'dead-tree-2',
  },
  'family-giant-pine': {
    label: 'Giant Pine',
    type: 'plant-family',
    familyVariants: [
      'tree-giant-pine-a',
      'tree-giant-pine-b',
      'tree-giant-pine-c',
      'tree-giant-pine-d',
      'tree-giant-pine-e',
    ],
    representativeModelKey: 'giant-pine-2',
  },
  'family-pine': {
    label: 'Pine',
    type: 'plant-family',
    familyVariants: [
      'tree-green-conifer',
      'tree-green-small',
      'tree-green-tall-columnar',
      'tree-green-columnar',
      'tree-green-small-oval',
      'tree-yellow-conifer',
    ],
    representativeModelKey: 'pine-conifer-2',
  },
  'family-deciduous': {
    label: 'Deciduous',
    type: 'plant-family',
    familyVariants: [
      'tree-green-deciduous',
      'tree-green-oval',
      'tree-green-willow',
      'tree-orange-deciduous',
      'tree-yellow-willow',
    ],
    representativeModelKey: 'common-broadleaf-2',
  },
  'family-crimson-remnant': {
    label: 'Crimson Remnant',
    type: 'plant-family',
    familyVariants: ['tree-dead-e'],
    representativeModelKey: 'twisted-bare-1',
  },
  'family-thick-trunk': {
    label: 'Thick Trunk',
    type: 'plant-family',
    familyVariants: [
      'tree-thick-a',
      'tree-thick-b',
      'tree-thick-c',
      'tree-thick-d',
      'tree-thick-e',
    ],
    representativeModelKey: 'tall-thick-2',
  },
  // Spectral uses thick trunk variants duplicated now (will customize later)
  'family-spectral': {
    label: 'Spectral',
    type: 'plant-family',
    familyVariants: [
      'tree-thick-a',
      'tree-thick-b',
      'tree-thick-c',
      'tree-thick-d',
      'tree-thick-e',
    ],
    representativeModelKey: 'tall-thick-3',
    spectral: true,
  },
  // Birch (temperate / mixed forests)
  'tree-birch-a': {
    label: 'Birch A',
    img: null,
    modelKey: 'birch-1',
    type: 'plant',
    scaleMode: 'contain',
    baselineOffsetPx: 16,
  },
  'tree-birch-b': {
    label: 'Birch B',
    img: null,
    modelKey: 'birch-2',
    type: 'plant',
    scaleMode: 'contain',
    baselineOffsetPx: 16,
  },
  'tree-birch-c': {
    label: 'Birch C',
    img: null,
    modelKey: 'birch-3',
    type: 'plant',
    scaleMode: 'contain',
    baselineOffsetPx: 16,
  },
  'tree-birch-d': {
    label: 'Birch D',
    img: null,
    modelKey: 'birch-4',
    type: 'plant',
    scaleMode: 'contain',
    baselineOffsetPx: 16,
  },
  'tree-birch-e': {
    label: 'Birch E',
    img: null,
    modelKey: 'birch-5',
    type: 'plant',
    scaleMode: 'contain',
    baselineOffsetPx: 16,
  },
  // Birch spectral (retain incorrect coloring as intentional fantasy variants)
  'tree-birch-a-spectral': {
    label: 'Birch A (Spectral)',
    img: null,
    modelKey: 'birch-1',
    type: 'plant',
    scaleMode: 'contain',
    baselineOffsetPx: 16,
    tintVariant: 'spectral',
  },
  'tree-birch-b-spectral': {
    label: 'Birch B (Spectral)',
    img: null,
    modelKey: 'birch-2',
    type: 'plant',
    scaleMode: 'contain',
    baselineOffsetPx: 16,
    tintVariant: 'spectral',
  },
  'tree-birch-c-spectral': {
    label: 'Birch C (Spectral)',
    img: null,
    modelKey: 'birch-3',
    type: 'plant',
    scaleMode: 'contain',
    baselineOffsetPx: 16,
    tintVariant: 'spectral',
  },
  'tree-birch-d-spectral': {
    label: 'Birch D (Spectral)',
    img: null,
    modelKey: 'birch-4',
    type: 'plant',
    scaleMode: 'contain',
    baselineOffsetPx: 16,
    tintVariant: 'spectral',
  },
  'tree-birch-e-spectral': {
    label: 'Birch E (Spectral)',
    img: null,
    modelKey: 'birch-5',
    type: 'plant',
    scaleMode: 'contain',
    baselineOffsetPx: 16,
    tintVariant: 'spectral',
  },
  // Cherry blossom (fantastical / mystic / fey)
  'tree-cherry-a': {
    label: 'Cherry A',
    img: null,
    modelKey: 'cherry-1',
    type: 'plant',
    scaleMode: 'contain',
    baselineOffsetPx: 16,
  },
  'tree-cherry-b': {
    label: 'Cherry B',
    img: null,
    modelKey: 'cherry-2',
    type: 'plant',
    scaleMode: 'contain',
    baselineOffsetPx: 16,
  },
  'tree-cherry-c': {
    label: 'Cherry C',
    img: null,
    modelKey: 'cherry-3',
    type: 'plant',
    scaleMode: 'contain',
    baselineOffsetPx: 16,
  },
  'tree-cherry-d': {
    label: 'Cherry D',
    img: null,
    modelKey: 'cherry-4',
    type: 'plant',
    scaleMode: 'contain',
    baselineOffsetPx: 16,
  },
  'tree-cherry-e': {
    label: 'Cherry E',
    img: null,
    modelKey: 'cherry-5',
    type: 'plant',
    scaleMode: 'contain',
    baselineOffsetPx: 16,
  },
  // Giant pines (alpine / mountain)
  'tree-giant-pine-a': {
    label: 'Giant Pine A',
    img: null,
    modelKey: 'giant-pine-1',
    type: 'plant',
    scaleMode: 'contain',
    baselineOffsetPx: 20,
  },
  'tree-giant-pine-b': {
    label: 'Giant Pine B',
    img: null,
    modelKey: 'giant-pine-2',
    type: 'plant',
    scaleMode: 'contain',
    baselineOffsetPx: 20,
  },
  'tree-giant-pine-c': {
    label: 'Giant Pine C',
    img: null,
    modelKey: 'giant-pine-3',
    type: 'plant',
    scaleMode: 'contain',
    baselineOffsetPx: 20,
  },
  'tree-giant-pine-d': {
    label: 'Giant Pine D',
    img: null,
    modelKey: 'giant-pine-4',
    type: 'plant',
    scaleMode: 'contain',
    baselineOffsetPx: 20,
  },
  'tree-giant-pine-e': {
    label: 'Giant Pine E',
    img: null,
    modelKey: 'giant-pine-5',
    type: 'plant',
    scaleMode: 'contain',
    baselineOffsetPx: 20,
  },
  // Dead trees (shadow / petrified / dead forests)
  'tree-dead-a': {
    label: 'Dead Tree A',
    img: null,
    modelKey: 'dead-tree-1',
    type: 'plant',
    scaleMode: 'contain',
    baselineOffsetPx: 16,
  },
  'tree-dead-b': {
    label: 'Dead Tree B',
    img: null,
    modelKey: 'dead-tree-2',
    type: 'plant',
    scaleMode: 'contain',
    baselineOffsetPx: 16,
  },
  'tree-dead-c': {
    label: 'Dead Tree C',
    img: null,
    modelKey: 'dead-tree-3',
    type: 'plant',
    scaleMode: 'contain',
    baselineOffsetPx: 16,
  },
  'tree-dead-d': {
    label: 'Dead Tree D',
    img: null,
    modelKey: 'dead-tree-4',
    type: 'plant',
    scaleMode: 'contain',
    baselineOffsetPx: 16,
  },
  'tree-dead-e': {
    label: 'Crimson Remnant',
    img: null,
    modelKey: 'twisted-bare-1',
    type: 'plant',
    scaleMode: 'contain',
    baselineOffsetPx: 16,
  },
  // Tall thick trunks (cedar highlands / ancient groves)
  'tree-thick-a': {
    label: 'Thick Trunk A',
    img: null,
    modelKey: 'tall-thick-1',
    type: 'plant',
    scaleMode: 'contain',
    baselineOffsetPx: 18,
  },
  'tree-thick-b': {
    label: 'Thick Trunk B',
    img: null,
    modelKey: 'tall-thick-2',
    type: 'plant',
    scaleMode: 'contain',
    baselineOffsetPx: 18,
  },
  'tree-thick-c': {
    label: 'Thick Trunk C',
    img: null,
    modelKey: 'tall-thick-3',
    type: 'plant',
    scaleMode: 'contain',
    baselineOffsetPx: 18,
  },
  'tree-thick-d': {
    label: 'Thick Trunk D',
    img: null,
    modelKey: 'tall-thick-4',
    type: 'plant',
    scaleMode: 'contain',
    baselineOffsetPx: 18,
  },
  'tree-thick-e': {
    label: 'Thick Trunk E',
    img: null,
    modelKey: 'tall-thick-5',
    type: 'plant',
    scaleMode: 'contain',
    baselineOffsetPx: 18,
  },
  // Understory - bushes
  'bush-common': {
    label: 'Bush',
    img: null,
    modelKey: 'bush-common',
    type: 'plant',
    scaleMode: 'contain',
    baselineOffsetPx: 8,
  },
  'bush-common-flowers': {
    label: 'Bush Flowers',
    img: null,
    modelKey: 'bush-common-flowers',
    type: 'plant',
    scaleMode: 'contain',
    baselineOffsetPx: 8,
  },
  'bush-large': {
    label: 'Bush Large',
    img: null,
    modelKey: 'bush-large',
    type: 'plant',
    scaleMode: 'contain',
    baselineOffsetPx: 10,
  },
  'bush-large-flowers': {
    label: 'Bush Large Flowers',
    img: null,
    modelKey: 'bush-large-flowers',
    type: 'plant',
    scaleMode: 'contain',
    baselineOffsetPx: 10,
  },
  'bush-long-1': {
    label: 'Bush Long 1',
    img: null,
    modelKey: 'bush-long-1',
    type: 'plant',
    scaleMode: 'contain',
    baselineOffsetPx: 8,
  },
  'bush-long-2': {
    label: 'Bush Long 2',
    img: null,
    modelKey: 'bush-long-2',
    type: 'plant',
    scaleMode: 'contain',
    baselineOffsetPx: 8,
  },
  // Flowers (can be used for mystical / meadow biomes)
  'flower-1-group': {
    label: 'Flowers 1 Group',
    img: null,
    modelKey: 'flower-1-group',
    type: 'plant',
    scaleMode: 'contain',
    baselineOffsetPx: 4,
  },
  'flower-1-single': {
    label: 'Flower 1 Single',
    img: null,
    modelKey: 'flower-1-single',
    type: 'plant',
    scaleMode: 'contain',
    baselineOffsetPx: 4,
  },
  'flower-2-group': {
    label: 'Flowers 2 Group',
    img: null,
    modelKey: 'flower-2-group',
    type: 'plant',
    scaleMode: 'contain',
    baselineOffsetPx: 4,
  },
  'flower-2-single': {
    label: 'Flower 2 Single',
    img: null,
    modelKey: 'flower-2-single',
    type: 'plant',
    scaleMode: 'contain',
    baselineOffsetPx: 4,
  },
  'flower-3-group': {
    label: 'Flowers 3 Group',
    img: null,
    modelKey: 'flower-3-group',
    type: 'plant',
    scaleMode: 'contain',
    baselineOffsetPx: 4,
  },
  'flower-3-single': {
    label: 'Flower 3 Single',
    img: null,
    modelKey: 'flower-3-single',
    type: 'plant',
    scaleMode: 'contain',
    baselineOffsetPx: 4,
  },
  'flower-4-group': {
    label: 'Flowers 4 Group',
    img: null,
    modelKey: 'flower-4-group',
    type: 'plant',
    scaleMode: 'contain',
    baselineOffsetPx: 4,
  },
  'flower-4-single': {
    label: 'Flower 4 Single',
    img: null,
    modelKey: 'flower-4-single',
    type: 'plant',
    scaleMode: 'contain',
    baselineOffsetPx: 4,
  },
  'flower-6': {
    label: 'Flower 6',
    img: null,
    modelKey: 'flower-6',
    type: 'plant',
    scaleMode: 'contain',
    baselineOffsetPx: 4,
  },
  'flower-6-2': {
    label: 'Flower 6-2',
    img: null,
    modelKey: 'flower-6-2',
    type: 'plant',
    scaleMode: 'contain',
    baselineOffsetPx: 4,
  },
  'flower-7-group': {
    label: 'Flowers 7 Group',
    img: null,
    modelKey: 'flower-7-group',
    type: 'plant',
    scaleMode: 'contain',
    baselineOffsetPx: 4,
  },
  'flower-7-single': {
    label: 'Flower 7 Single',
    img: null,
    modelKey: 'flower-7-single',
    type: 'plant',
    scaleMode: 'contain',
    baselineOffsetPx: 4,
  },
  // Mushrooms (swamp / fungal / shadow biomes)
  'mushroom-common': {
    label: 'Mushroom Common',
    img: null,
    modelKey: 'mushroom-common',
    type: 'plant',
    scaleMode: 'contain',
    baselineOffsetPx: 2,
  },
  'mushroom-redcap': {
    label: 'Mushroom Redcap',
    img: null,
    modelKey: 'mushroom-redcap',
    type: 'plant',
    scaleMode: 'contain',
    baselineOffsetPx: 2,
  },
  'mushroom-oyster': {
    label: 'Mushroom Oyster',
    img: null,
    modelKey: 'mushroom-oyster',
    type: 'plant',
    scaleMode: 'contain',
    baselineOffsetPx: 2,
  },
  'mushroom-laetiporus': {
    label: 'Mushroom Laetiporus',
    img: null,
    modelKey: 'mushroom-laetiporus',
    type: 'plant',
    scaleMode: 'contain',
    baselineOffsetPx: 2,
  },
  // Grasses
  'grass-common-short': {
    label: 'Grass Common Short',
    img: null,
    modelKey: 'grass-common-short',
    type: 'plant',
    scaleMode: 'contain',
    baselineOffsetPx: 0,
  },
  'grass-common-tall': {
    label: 'Grass Common Tall',
    img: null,
    modelKey: 'grass-common-tall',
    type: 'plant',
    scaleMode: 'contain',
    baselineOffsetPx: 0,
  },
  'grass-wide-short': {
    label: 'Grass Wide Short',
    img: null,
    modelKey: 'grass-wide-short',
    type: 'plant',
    scaleMode: 'contain',
    baselineOffsetPx: 0,
  },
  'grass-wide-tall': {
    label: 'Grass Wide Tall',
    img: null,
    modelKey: 'grass-wide-tall',
    type: 'plant',
    scaleMode: 'contain',
    baselineOffsetPx: 0,
  },
  'grass-wispy-short': {
    label: 'Grass Wispy Short',
    img: null,
    modelKey: 'grass-wispy-short',
    type: 'plant',
    scaleMode: 'contain',
    baselineOffsetPx: 0,
  },
  'grass-wispy-tall': {
    label: 'Grass Wispy Tall',
    img: null,
    modelKey: 'grass-wispy-tall',
    type: 'plant',
    scaleMode: 'contain',
    baselineOffsetPx: 0,
  },
  'grass-wheat': {
    label: 'Grass Wheat',
    img: null,
    modelKey: 'grass-wheat',
    type: 'plant',
    scaleMode: 'contain',
    baselineOffsetPx: 0,
  },
  // Rocks / pebbles (as placeable decorative plants for variety layering)
  'rock-medium-4': {
    label: 'Rock Medium 4',
    img: null,
    modelKey: 'rock-medium-4',
    type: 'plant',
    scaleMode: 'contain',
    baselineOffsetPx: 0,
  },
  'rock-big-1': {
    label: 'Rock Big 1',
    img: null,
    modelKey: 'rock-big-1',
    type: 'plant',
    scaleMode: 'contain',
    baselineOffsetPx: 0,
  },
  'rock-big-2': {
    label: 'Rock Big 2',
    img: null,
    modelKey: 'rock-big-2',
    type: 'plant',
    scaleMode: 'contain',
    baselineOffsetPx: 0,
  },
  'pebble-round-1': {
    label: 'Pebble Round 1',
    img: null,
    modelKey: 'pebble-round-1',
    type: 'plant',
    scaleMode: 'contain',
    baselineOffsetPx: 0,
  },
  'pebble-round-2': {
    label: 'Pebble Round 2',
    img: null,
    modelKey: 'pebble-round-2',
    type: 'plant',
    scaleMode: 'contain',
    baselineOffsetPx: 0,
  },
  'pebble-round-3': {
    label: 'Pebble Round 3',
    img: null,
    modelKey: 'pebble-round-3',
    type: 'plant',
    scaleMode: 'contain',
    baselineOffsetPx: 0,
  },
  'pebble-round-4': {
    label: 'Pebble Round 4',
    img: null,
    modelKey: 'pebble-round-4',
    type: 'plant',
    scaleMode: 'contain',
    baselineOffsetPx: 0,
  },
  'pebble-round-5': {
    label: 'Pebble Round 5',
    img: null,
    modelKey: 'pebble-round-5',
    type: 'plant',
    scaleMode: 'contain',
    baselineOffsetPx: 0,
  },
  'pebble-square-1': {
    label: 'Pebble Square 1',
    img: null,
    modelKey: 'pebble-square-1',
    type: 'plant',
    scaleMode: 'contain',
    baselineOffsetPx: 0,
  },
  'pebble-square-2': {
    img: null,
    modelKey: 'pebble-square-2',
    type: 'plant',
    scaleMode: 'contain',
    baselineOffsetPx: 0,
  },
  'pebble-square-3': {
    label: 'Pebble Square 3',
    img: null,
    modelKey: 'pebble-square-3',
    type: 'plant',
    scaleMode: 'contain',
    baselineOffsetPx: 0,
  },
  'pebble-square-4': {
    label: 'Pebble Square 4',
    img: null,
    modelKey: 'pebble-square-4',
    type: 'plant',
    scaleMode: 'contain',
    baselineOffsetPx: 0,
  },
  'pebble-square-5': {
    label: 'Pebble Square 5',
    img: null,
    modelKey: 'pebble-square-5',
    type: 'plant',
    scaleMode: 'contain',
    baselineOffsetPx: 0,
  },
  'pebble-square-6': {
    label: 'Pebble Square 6',
    img: null,
    modelKey: 'pebble-square-6',
    type: 'plant',
    scaleMode: 'contain',
    baselineOffsetPx: 0,
  },
};

// Merge TREE_PLACEABLES into TERRAIN_PLACEABLES so existing code can reference
// all placeables from a single exported object.
Object.entries(TREE_PLACEABLES).forEach(([k, v]) => {
  TERRAIN_PLACEABLES[k] = v;
});

// (Former forest billboard experimental group removed; placeholder comments pruned.)
